# Generated by Django 6.0.4 on 2026-04-09 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_auxplatform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('idle', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], default=False, verbose_name='Inativo?')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome do Módulo')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug (Identificador Único)')),
                ('module_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.auxmoduletype', verbose_name='Tipo de Módulo')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.auxplatform', verbose_name='Plataforma Alvo')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'db_table': 'modules',
                'ordering': ['name'],
            },
        ),
    ]
