# Generated by Django 6.0.4 on 2026-04-09 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('idle', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], default=False, verbose_name='Inativo?')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID da Licença')),
                ('site_url', models.URLField(max_length=255, verbose_name='URL do Site')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Licença',
                'verbose_name_plural': 'Licenças',
                'db_table': 'licenses',
                'ordering': ['client', 'site_url'],
            },
        ),
    ]
