# Generated by Django 6.0.4 on 2026-04-09 18:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseModulePermission',
            fields=[
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('idle', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], default=False, verbose_name='Inativo?')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID da Permissão')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado?')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='licenses.license', verbose_name='Licença')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses_permissions', to='modules.module', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Permissão de Módulo',
                'verbose_name_plural': 'Permissões de Módulos',
                'db_table': 'license_module_permission',
                'constraints': [models.UniqueConstraint(fields=('license', 'module'), name='unique_license_module')],
            },
        ),
    ]
