# Generated by Django 6.0.3 on 2026-04-09 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('idle', models.BooleanField(choices=[(False, 'Não'), (True, 'Sim')], default=False, verbose_name='Inativo?')),
                ('uid', models.BigIntegerField(unique=True, verbose_name='UID (Código Único)')),
                ('name', models.CharField(max_length=255, verbose_name='Nome / Razão Social')),
                ('fantasy_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('person_type', models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], default='J', max_length=1, verbose_name='Tipo de Pessoa')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ')),
                ('rg_ie', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG / Inscrição Estadual')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clients',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cpf_cnpj__isnull', False), models.Q(('cpf_cnpj', ''), _negated=True)), fields=('cpf_cnpj',), name='unique_cpf_cnpj_not_null')],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('value', models.CharField(max_length=255, verbose_name='Valor (Tel/Email)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client', verbose_name='Cliente')),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.auxcontacttype', verbose_name='Tipo de Contato')),
            ],
            options={
                'verbose_name': 'Contato do Cliente',
                'verbose_name_plural': 'Contatos dos Clientes',
                'db_table': 'clients_contacts',
            },
        ),
    ]
