# Generated by Django 6.0.4 on 2026-04-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='uid',
            field=models.BigIntegerField(blank=True, unique=True, verbose_name='UID (Código Único)'),
        ),
    ]
