# Generated by Django 6.0.4 on 2026-04-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='uid',
            field=models.BigIntegerField(editable=False, unique=True, verbose_name='UID (Código Único)'),
        ),
    ]
