# Generated by Django 6.0.4 on 2026-04-09 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenses', '0002_licensemodulepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Informação'), ('WARN', 'Aviso'), ('ERR', 'Erro Crítico'), ('AUDIT', 'Auditoria/Segurança')], default='INFO', max_length=5, verbose_name='Nível do Log')),
                ('module_slug', models.CharField(blank=True, max_length=100, null=True, verbose_name='Slug do Módulo')),
                ('message', models.TextField(verbose_name='Mensagem / Descrição')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Dados Extras (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_logs', to='licenses.license', verbose_name='Licença')),
            ],
            options={
                'verbose_name': 'Log de Telemetria',
                'verbose_name_plural': 'Logs de Telemetria',
                'db_table': 'telemetry_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
